//! Basic detour candidate generation and scoring.

use crate::nav::distance::{euclidean_distance_raw, raw_distance_to_parsec};
use crate::nav::geometry::{left_normal, normalize2};
use crate::nav::models::{
    DetourCandidate, Obstacle, ObstacleCheck, Planet, RouteOptions, RouteWaypoint,
};
use crate::nav::obstacle::check_obstacle_against_route;

const TURN_WEIGHT: f64 = 0.8;
const BACK_WEIGHT: f64 = 3.0;
const PROXIMITY_MARGIN: f64 = 0.5;

/// Multiplier used to amplify turn penalties into route-score space.
const TURN_SCORE_FACTOR: f64 = 1_000.0;

/// Multiplier used to amplify backtracking penalties into route-score space.
const BACK_SCORE_FACTOR: f64 = 1_000.0;

/// Multiplier used to amplify proximity penalties into route-score space.
const PROXIMITY_SCORE_FACTOR: f64 = 10_000.0;

const PROXIMITY_COMFORT_MARGIN: f64 = 3.0;

const OFFSET_WEIGHT: f64 = 0.5;

/// Builds two detour candidates around a violating obstacle using a specified offset.
///
/// The candidates are generated by offsetting from the obstacle center
/// along the normal to the original route segment.
pub fn generate_detour_candidates_with_offset(
    from: &Planet,
    to: &Planet,
    violation: &ObstacleCheck,
    offset: f64,
) -> Vec<DetourCandidate> {
    let seg_x = to.x - from.x;
    let seg_y = to.y - from.y;

    let (dir_x, dir_y) = normalize2(seg_x, seg_y);
    let (nx, ny) = left_normal(dir_x, dir_y);

    let left = DetourCandidate {
        waypoint: RouteWaypoint {
            x: violation.obstacle_x + nx * offset,
            y: violation.obstacle_y + ny * offset,
        },
        side: "left".to_string(),
        offset_used: offset,
        base_distance: 0.0,
        turn_penalty: 0.0,
        back_penalty: 0.0,
        proximity_penalty: 0.0,
        total_score: 0.0,
        is_valid: false,
        rejection_reason: None,
        offset_penalty: 0.0,
    };

    let right = DetourCandidate {
        waypoint: RouteWaypoint {
            x: violation.obstacle_x - nx * offset,
            y: violation.obstacle_y - ny * offset,
        },
        side: "right".to_string(),
        offset_used: offset,
        base_distance: 0.0,
        turn_penalty: 0.0,
        back_penalty: 0.0,
        proximity_penalty: 0.0,
        total_score: 0.0,
        is_valid: false,
        rejection_reason: None,
        offset_penalty: 0.0,
    };

    vec![left, right]
}

/// Computes the raw total distance of a route split into two legs.
///
/// Route:
/// `from -> waypoint -> to`
pub fn compute_detour_raw_distance(from: &Planet, to: &Planet, waypoint: &RouteWaypoint) -> f64 {
    let wp_planet = Planet {
        id: -1,
        name: "detour".to_string(),
        x: waypoint.x,
        y: waypoint.y,
        z: 0.0,
    };

    euclidean_distance_raw(from, &wp_planet) + euclidean_distance_raw(&wp_planet, to)
}

/// Computes the total detour distance in parsecs.
pub fn compute_detour_distance_parsec(from: &Planet, to: &Planet, waypoint: &RouteWaypoint) -> f64 {
    raw_distance_to_parsec(compute_detour_raw_distance(from, to, waypoint))
}

fn dot(ax: f64, ay: f64, bx: f64, by: f64) -> f64 {
    ax * bx + ay * by
}

/// Evaluates one detour candidate and returns a scored copy.
pub fn evaluate_detour_candidate(
    from: &Planet,
    to: &Planet,
    obstacle: &Obstacle,
    candidate: &DetourCandidate,
    route_clearance: f64,
) -> DetourCandidate {
    let wp_planet = Planet {
        id: -1,
        name: "detour".to_string(),
        x: candidate.waypoint.x,
        y: candidate.waypoint.y,
        z: 0.0,
    };

    let first_check = check_obstacle_against_route(from, &wp_planet, obstacle, route_clearance);
    let second_check = check_obstacle_against_route(&wp_planet, to, obstacle, route_clearance);

    if first_check.is_violating {
        let mut rejected = candidate.clone();
        rejected.is_valid = false;
        rejected.rejection_reason = Some("first leg still collides".to_string());
        return rejected;
    }

    if second_check.is_violating {
        let mut rejected = candidate.clone();
        rejected.is_valid = false;
        rejected.rejection_reason = Some("second leg still collides".to_string());
        return rejected;
    }

    let base_distance = compute_detour_raw_distance(from, to, &candidate.waypoint);

    let leg1_x = candidate.waypoint.x - from.x;
    let leg1_y = candidate.waypoint.y - from.y;
    let leg2_x = to.x - candidate.waypoint.x;
    let leg2_y = to.y - candidate.waypoint.y;

    let (dir1_x, dir1_y) = normalize2(leg1_x, leg1_y);
    let (dir2_x, dir2_y) = normalize2(leg2_x, leg2_y);

    let turn_cos = dot(dir1_x, dir1_y, dir2_x, dir2_y).clamp(-1.0, 1.0);
    let turn_penalty = (1.0 - turn_cos) * TURN_WEIGHT * TURN_SCORE_FACTOR;

    let seg_x = to.x - from.x;
    let seg_y = to.y - from.y;
    let (route_dir_x, route_dir_y) = normalize2(seg_x, seg_y);

    let forward_dot = dot(route_dir_x, route_dir_y, dir1_x, dir1_y);
    let back_penalty = if forward_dot < 0.0 {
        (-forward_dot) * BACK_WEIGHT * BACK_SCORE_FACTOR
    } else {
        0.0
    };

    let min_clearance = first_check
        .closest_distance
        .min(second_check.closest_distance);

    let desired_clearance = obstacle.radius + route_clearance + PROXIMITY_MARGIN;
    let comfort_clearance = obstacle.radius + route_clearance + PROXIMITY_COMFORT_MARGIN;

    let hard_gap = (desired_clearance - min_clearance).max(0.0);
    let soft_gap = (comfort_clearance - min_clearance).max(0.0);

    let proximity_penalty = hard_gap * hard_gap * PROXIMITY_SCORE_FACTOR
        + soft_gap * soft_gap * (PROXIMITY_SCORE_FACTOR * 0.25);

    let required_clearance = obstacle.radius + route_clearance;
    let extra_offset = (candidate.offset_used - required_clearance).max(0.0);
    let offset_penalty = extra_offset * OFFSET_WEIGHT;

    let total_score =
        base_distance + turn_penalty + back_penalty + proximity_penalty + offset_penalty;

    DetourCandidate {
        waypoint: candidate.waypoint.clone(),
        side: candidate.side.clone(),
        offset_used: candidate.offset_used,
        base_distance,
        turn_penalty,
        back_penalty,
        proximity_penalty,
        total_score,
        is_valid: true,
        rejection_reason: None,
        offset_penalty,
    }
}

/// Evaluates all candidates produced by offset growth and returns:
/// - all evaluated candidates
/// - the best valid candidate, if any
pub fn evaluate_detour_with_offset_growth(
    from: &Planet,
    to: &Planet,
    obstacle: &Obstacle,
    violation: &ObstacleCheck,
    options: RouteOptions,
) -> (Vec<DetourCandidate>, Option<DetourCandidate>) {
    let base_offset = violation.required_clearance;
    let mut evaluated = Vec::new();
    let mut best: Option<DetourCandidate> = None;

    for attempt in 0..options.max_offset_tries {
        let offset = base_offset * options.offset_growth.powi(attempt as i32);
        let generated = generate_detour_candidates_with_offset(from, to, violation, offset);

        for candidate in generated {
            let scored =
                evaluate_detour_candidate(from, to, obstacle, &candidate, options.clearance);

            if scored.is_valid {
                match &best {
                    Some(current_best) if scored.total_score >= current_best.total_score => {}
                    _ => best = Some(scored.clone()),
                }
            }

            evaluated.push(scored);
        }
    }

    (evaluated, best)
}
